"""
CBIS-DDSM (Kaggle awsaf49 bundle) path helpers and manifest builders.

Expected layout under dataset root:
  csv/  (mass_case_description_* , calc_case_description_* , dicom_info.csv)
  jpeg/ (tree referenced by CSV paths)
"""
from __future__ import annotations

import os
import random
import re
from typing import Iterable

import pandas as pd


def _norm_key(name: str) -> str:
    return re.sub(r"\s+", "", name).lower()


def column_lookup(df: pd.DataFrame) -> dict[str, str]:
    return {_norm_key(c): c for c in df.columns}


def pick_column(df: pd.DataFrame, *candidates: str) -> str | None:
    cmap = column_lookup(df)
    for c in candidates:
        k = _norm_key(c)
        if k in cmap:
            return cmap[k]
    return None


_PATIENT_TOKEN = re.compile(r"(P_\d+)", re.IGNORECASE)


def _clean_path_cell(raw: object) -> str:
    if raw is None or (isinstance(raw, float) and pd.isna(raw)):
        return ""
    s = str(raw).strip().replace("\\", "/")
    s = s.split("\n")[0].strip().strip('"').strip()
    return s


def resolve_cbis_path(raw: object, dataset_root: str) -> str:
    """Map a path from CBIS CSV to a local filesystem path (Kaggle uses jpeg/*.jpg)."""
    s = _clean_path_cell(raw)
    if not s:
        return ""
    root = os.path.abspath(dataset_root)
    if "CBIS-DDSM" in s:
        idx = s.find("CBIS-DDSM")
        tail = s[idx + len("CBIS-DDSM") :].lstrip("/")
        candidate = os.path.normpath(os.path.join(root, tail))
    elif s.lower().startswith("jpeg/"):
        candidate = os.path.normpath(os.path.join(root, s))
    else:
        candidate = os.path.normpath(os.path.join(root, "jpeg", s.lstrip("/")))

    if os.path.isfile(candidate):
        return candidate
    base, ext = os.path.splitext(candidate)
    if ext.lower() == ".dcm":
        for e in (".jpg", ".jpeg", ".png", ".dcm"):
            alt = base + e
            if os.path.isfile(alt):
                return alt
        return base + ".jpg"
    return candidate


def _read_case_csvs(
    dataset_root: str, which: Iterable[str]
) -> list[tuple[str, pd.DataFrame]]:
    out: list[tuple[str, pd.DataFrame]] = []
    csv_dir = os.path.join(dataset_root, "csv")
    for name in which:
        p = os.path.join(csv_dir, name)
        if not os.path.isfile(p):
            continue
        out.append((name, pd.read_csv(p)))
    return out


_JPEG_UID_RE = re.compile(r"jpeg/([0-9.]+)/", re.IGNORECASE)


def _uid_jpeg_maps_from_dicom(dicom: pd.DataFrame, dataset_root: str) -> tuple[dict[str, str], dict[str, str]]:
    """
    Map SeriesInstanceUID-style folder (numeric.dots under jpeg/) to one crop JPEG and one ROI mask JPEG.
    CBIS case CSV paths do not match on-disk layout; dicom_info.csv is authoritative.
    """
    c_img = pick_column(dicom, "image_path", "ImagePath")
    c_series = pick_column(dicom, "SeriesDescription", "Series Description")
    crop_by_uid: dict[str, str] = {}
    mask_by_uid: dict[str, str] = {}
    if not c_img or not c_series:
        return crop_by_uid, mask_by_uid
    for _, row in dicom.iterrows():
        if pd.isna(row.get(c_img)) or pd.isna(row.get(c_series)):
            continue
        raw_ip = str(row[c_img])
        m = _JPEG_UID_RE.search(raw_ip.replace("\\", "/"))
        if not m:
            continue
        uid = m.group(1)
        full = resolve_cbis_path(raw_ip, dataset_root)
        if not full or not os.path.isfile(full):
            continue
        sd = str(row[c_series]).lower()
        if "cropped images" in sd:
            crop_by_uid.setdefault(uid, full)
        elif "roi mask" in sd:
            mask_by_uid.setdefault(uid, full)
    return crop_by_uid, mask_by_uid


def collect_abnormal_patient_tokens(dataset_root: str) -> set[str]:
    """Normalized P_XXXXX tokens for patients with annotated masses or calcifications."""
    ids: set[str] = set()
    case_names = [
        "mass_case_description_train_set.csv",
        "mass_case_description_test_set.csv",
        "calc_case_description_train_set.csv",
        "calc_case_description_test_set.csv",
    ]
    for _, df in _read_case_csvs(dataset_root, case_names):
        for _, row in df.iterrows():
            for c in df.columns:
                if df[c].dtype != object:
                    continue
                val = row.get(c)
                if val is None or (isinstance(val, float) and pd.isna(val)):
                    continue
                m = _PATIENT_TOKEN.search(str(val))
                if m:
                    ids.add(m.group(1).upper())
    return ids


def build_segmentation_manifest(dataset_root: str = "") -> pd.DataFrame:
    """
    Deprecated: The legacy on-the-fly loading from Kaggle DICOMs is no longer supported.
    Use the offline preprocessed dataset generated by `scripts/preprocess_cbis.py`.
    """
    import warnings
    warnings.warn("Use preprocess_cbis.py output instead of build_segmentation_manifest.")
    return pd.DataFrame()

def build_classification_manifest(
    dataset_root: str,
    max_normal: int = 4000,
    random_seed: int = 42,
) -> pd.DataFrame:
    return pd.DataFrame()

def write_manifests(dataset_root: str, out_dir: str) -> tuple[str, str]:
    import sys
    print("ERROR: Legacy manifest building is strictly deprecated.")
    print("Please run: python scripts/preprocess_cbis.py --data-root <path>")
    sys.exit(1)
